modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ConsistencyPlus/ConsistencyPlus/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "consistency_plus"
version = "${version}"
displayName = "Consistency Plus"
displayURL = "https://github.com/ConsistencyPlus/ConsistencyPlus"
authors = [
    "Carter",
    "Siuol",
    "Tropheus Jay",
    "IMS",
    "Devious",
    "Emmaffle",
    "Ibex",
    "Tyler",
    "Pepper",
    "Devin",
    "Jingy",
    "Seska",
    "RDKRACZ",
    "MobButcher",
    "Dodomos"
]
description = '''
Builders rejoice; we've added all the missing block variants (and a whole lot more)!
'''
logoFile = "icon.png"

[[dependencies.consistency_plus]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.consistency_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.consistency_plus]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.30,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.consistency_plus]]
modId = "stonecutter_recipe_tags"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"
