modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ConsistencyPlus/ConsistencyPlus/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "consistency_plus"
version = "${version}"
displayName = "Consistency Plus"
displayURL = "https://github.com/ConsistencyPlus/ConsistencyPlus"
authors = [
    "Carter [Project Lead]",
    "Siuol [Assistant Project Lead]",
    "Tropheus Jay [Assistant Project Lead]",
    "IMS [Former Developer]",
    "Devious [Generator Developer]",
    "Emmaffle [Developer]",
    "Andrew Grant [Developer]",
    "Blodhgarm [Contributor]",
    "Ibex [Contributor]",
    "Tyler [Contributor]",
    "Pepper [Contributor]",
    "Devin [Contributor]",
    "Pythagoras341 [Texture Artist]",
    "CLASSICA! [Texture Artist]",
    "Jingy [Texture Contributor]",
    "Seska [Texture Contributor]",
    "ParanormalChicken [Translator/Texture Contributor]",
    "RDKRACZ [Translator]",
    "MobButcher [Translator]",
    "Dodomos [Translator]"
]
description = '''
Builders rejoice; we've added all the missing block variants (and a whole lot more)!
'''
logoFile = "icon.png"

[[dependencies.consistency_plus]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0, 47.1.3]"
ordering = "NONE"
side = "BOTH"

[[dependencies.consistency_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
