name: Publish C+
on:
  push:
    branches:
      - master
      - maven-publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: ./gradlew publishAllPublicationsToEmmavenSnapshotsRepository
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
