name: Build C+
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: |
          sudo snap install -y deno
          sudo snap install -y oxipng
          ./gradlew build
          deno run --allow-read --allow-write --allow-run --unstable https://raw.githubusercontent.com/EnnuiL/Detonater/main/mod.ts folder build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: detonatedmods/
