name: Build C+
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Get Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Get Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.15.3
      - name: Get Oxipng
        run: |
          wget https://github.com/shssoichiro/oxipng/releases/download/v5.0.0/oxipng-5.0.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf oxipng-5.0.0-x86_64-unknown-linux-musl.tar.gz
          sudo mv ./oxipng-5.0.0-x86_64-unknown-linux-musl/oxipng /bin/
          chmod +x /bin/oxipng
      - name: Build projects and remove dev jars
        run: |
          ./gradlew build
          rm common/build/libs/**-dev.jar
          rm fabric/build/libs/**-dev.jar
          rm forge/build/libs/**-dev.jar
        env:
          SNAPSHOT: ""
      - run: |
          alias detonate="deno run --allow-read --allow-write --allow-run --unstable https://raw.githubusercontent.com/EnnuiL/Detonater/main/mod.ts"
          detonate folder common/build/libs/
          detonate folder fabric/build/libs/
          detonate folder forge/build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Common Artifacts
          path: common/build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Forge Artifacts
          path: forge/build/libs/
