name: Release C+
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - run: |
          wget https://github.com/shssoichiro/oxipng/releases/download/v5.0.0/oxipng-5.0.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf oxipng-5.0.0-x86_64-unknown-linux-musl.tar.gz
          sudo mv ./oxipng-5.0.0-x86_64-unknown-linux-musl/oxipng /bin/
          chmod +x /bin/oxipng
      - run: ./gradlew build
      - run: deno run --allow-read --allow-write --allow-run --unstable https://raw.githubusercontent.com/EnnuiL/Detonater/main/mod.ts folder build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: detonatedmods/
      - run: ./gradlew publishAllPublicationsToEmmavenReleasesRepository
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
